

class MediaProfileSpecType():
    WEBM = "WEBM",
    MP4 = "MP4",
    WEBM_VIDEO_ONLY = "WEBM_VIDEO_ONLY",
    WEBM_AUDIO_ONLY = "WEBM_AUDIO_ONLY",
    MP4_VIDEO_ONLY = "MP4_VIDEO_ONLY",
    MP4_AUDIO_ONLY = "MP4_AUDIO_ONLY",
    JPEG_VIDEO_ONLY = "JPEG_VIDEO_ONLY",
    KURENTO_SPLIT_RECORDER = "KURENTO_SPLIT_RECORDER"